doctrine:
    dbal:
        #        url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dbname: '%env(DATABASE_DBNAME)%'
                driver_class: App\Doctrine\ClickHouseDriver
                wrapper_class: App\Doctrine\Connection
                options:
                    enable_http_compression: 1
                    max_execution_time: 60
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            date: App\Doctrine\Types\DateType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
        # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
